setup: |
  echo "🐊 Attempt to install exposition engineering tools"
  echo "🐊 Using pipx to perform program installation"
  echo "🐊 Will not re-install if already installed"
  pipx install pymarkdownlnt
---

# Checks on Files {{{

# perform checks on a file
- writing/podcast_peer_reviews.md:
    - description: Ensure that the podcast_peer_reviews.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Retype the every word in the Honor Code pledge in reflection.md
      check: MatchFileFragment
      options:
        fragment: "I adhered to the Allegheny College Honor Code while completing this project."
        count: 2
        exact: true
    - description: Confirm that the markdown file containing the podcast peer reviews has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 10
        exact: true
    - description: Confirm that the markdown file containing the podcast peer reviews has a link to peer review 1
      check: MatchFileFragment
      options:
        fragment: "**Link to Peer Review 1**:"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the podcast peer reviews has a link to peer review 2
      check: MatchFileFragment
      options:
        fragment: "**Link to Peer Review 2**:"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the podcast peer reviews has a link to peer review 3
      check: MatchFileFragment
      options:
        fragment: "**Link to Peer Review 3**:"
        count: 1
        exact: true

# }}}

# Check Output from Linters {{{

# run a check
- description: Confirm that the show characterization file passes the linting checks run by pymarkdownlnt
  command: "pymarkdown --config .pymarkdown.cfg scan writing/podcast_peer_reviews.md"

# }}}

# Commits {{{

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 5

# }}}
